# Configuration file

title: Jekyll Theme Vita
description: Minimal and elegant Jekyll theme for personal website. 
url: ''
baseurl: '/jekyll-theme-vita'

# Language. Use ISO 639-1. Examples: if english use 'en',
# if spanish use 'es'
language: en

# ----------------------------------------------------------

permalink: /:categories/:year/:month/:day/:title:output_ext

collections_dir: collections
collections:
  projects:
    output: true

defaults:
  - scope:
      path: ''
    values:
      layout: 'default-center'
  - scope:
      path: 'collections/_posts'
    values:
      layout: 'post'

sass:
  style: compressed

plugins:
  - jekyll-sitemap
