# Configuration file

title: Jekyll Theme Vita
description: Minimal and elegant Jekyll theme for personal website. 
url: 'https://martinmorando.github.io'
baseurl: '/jekyll-theme-vita'

# Language. Use ISO 639-1. Examples: if english use 'en',
# if spanish use 'es'
language: en

# ----------------------------------------------------------

permalink: /:year/:month/:day/:title:output_ext

collections_dir: collections
collections:
  projects:
    output: true

defaults:
  - scope:
      path: ''
    values:
      layout: 'default-center'
  - scope:
      path: 'pages'
    values:
      layout: 'page'
  - scope:
      path: 'collections/_posts'
    values:
      layout: 'post'
  - scope:
      path: 'collections/_projects'
    values:
      layout: 'project'

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate-v2

# jekyll-archives to display categories and tags
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: /blog/categories/:name/
    tag: /blog/tags/:name/

# jekyll-paginate-v2 for pagination of posts
pagination:
  enabled: true
  collection: 'posts'
  per_page: 3
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

compress_html:
  clippings: all
  comments: false
  endings: all
  blanklines: false
  profile: false 