title: Jekyll Theme Vita
description: Pending description
url: ''
language: en

baseurl: '/jekyll-theme-vita'

permalink: /:categories/:year/:month/:day/:title:output_ext

collections_dir: collections
collections:
  projects:
    output: true

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'